### ISSUE TITLE
[Bug] unsupported operand type(s) for /: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Mokson** [jfarmer08/ha-sengledapi#24]
Hi,

I've faced with the below error message on the latest build.

I have E21-G14 W hub with white A19 bulbs (Sengled Smart LED Soft White A19 Kit)

```
2020-09-14 13:41:16 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'ret': 0, 'msg': 'success', 'customerId': 19146, 'mobileId': 103763, 'nick_name': 'Max', 'relative_path': None, 'jsessionId': 'daa5577d-6b5c-4e51-a2a0-9a8651a849d4', 'ucenterAddr': '', 'appServerAddr': '', 'serAddressess': None, 'privacyPolicyStatus': 1}
2020-09-14 13:41:16 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi Login {'ret': 0, 'msg': 'success', 'customerId': 19146, 'mobileId': 103763, 'nick_name': 'Max', 'relative_path': None, 'jsessionId': 'daa5577d-6b5c-4e51-a2a0-9a8651a849d4', 'ucenterAddr': '', 'appServerAddr': '', 'serAddressess': None, 'privacyPolicyStatus': 1}
2020-09-14 13:41:16 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:16 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:18 WARNING (MainThread) [homeassistant.setup] Setup of sengledapi is taking over 10 seconds.
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get MQTT Server Info{'messageCode': '200', 'info': 'OK', 'description': '正常', 'jbalancerAddr': 'https://eu-life2.cloud.sengled.com:443/jbalancer/new/bimqtt', 'inceptionAddr': 'wss://eu-mqtt.cloud.sengled.com:443/mqtt', 'appServerAddr': 'https://eu-life2.cloud.sengled.com:443/life2/', 'inceptionIp': '18.195.119.104', 'mqttSslPort': 6884, 'opsMgtUrl': 'https://eu-ops-mgt.cloud.sengled.com:443/ops-mgt', 'success': True}
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Parese MQTT Server InfoParseResult(scheme='wss', netloc='eu-mqtt.cloud.sengled.com:443', path='/mqtt', params='', query='', fragment='')
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Login initialize mqtt client None
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Initialize the MQTT connection
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Start mqtt loop
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Connected to Sengled account
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:20 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Store the logged in account object for the platforms to use
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Start up lights, switch and binary sensor components
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.light] Creating new Sengled light component
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List All Bulbs.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List Device return {'gatewayUuid': 'B0:CE:18:24:51:71', 'gatewayName': 'Hub', 'routerBssid': '02:00:00:00:00:00', 'activeTime': '2018-12-26 22:21:25', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.1.20', 'isOnline': 1, 'ssid': 'RTK 11n AP', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/Kiev', 'lampInfos': [{'deviceUuid': 'B0CE1814033599A1', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 2', 'colorMode': '3', 'isOnline': '0', 'version': '9', 'onCount': '269', 'typeCode': 'E11-G13', 'onoff': '0'}}, {'deviceUuid': 'B0CE181403359E4B', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '3', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 1', 'colorMode': '3', 'isOnline': '1', 'version': '9', 'onCount': '289', 'typeCode': 'E11-G13', 'onoff': '1'}}]}
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] SengledApi: Bulb Bedroom Bulb 2 initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] SengledApi: Bulb Bedroom Bulb 1 initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 2 B0CE1814033599A1 updating.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 1 B0CE181403359E4B updating.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 13:41:21 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 13:41:22 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Light Bedroom Bulb 1 updating.
2020-09-14 13:41:22 ERROR (MainThread) [homeassistant.components.light] Error while setting up sengledapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 192, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 474, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 442, in state_attributes
    data[ATTR_COLOR_TEMP] = self.color_temp
  File "/config/custom_components/sengledapi/light.py", line 97, in color_temp
    return colorutil.color_temperature_kelvin_to_mired(self._color_temperature)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 515, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
2020-09-14 13:41:22 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Light Bedroom Bulb 2 updating.
2020-09-14 13:41:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 442, in state_attributes
    data[ATTR_COLOR_TEMP] = self.color_temp
  File "/config/custom_components/sengledapi/light.py", line 97, in color_temp
    return colorutil.color_temperature_kelvin_to_mired(self._color_temperature)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 515, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
```

![image](https://user-images.githubusercontent.com/41159986/93076723-72cd4480-f690-11ea-8b91-f7b40341a9bc.png)

**Comment by jfarmer08** [comment]
I have made a couple of updates can you pull down the master branch and update your system>
https://github.com/jfarmer08/ha-sengledapi

**Comment by Mokson** [comment]
Thanks! This bug is fixed now.

I'm seeing another issue, but it was also in the previous version.

 [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sengledapi doing I/O at custom_components/sengledapi/sengledapi/sengled_request.py, line 39: r = requests.post(self._url, headers=self._header, data=self._payload)

```
2020-09-14 18:05:11 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Light Bedroom Bulb 2 updating.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] SengledApi: Bulb Bedroom Bulb 2 B0CE1814033599A1 turning on.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] SengledApi: Bulb Bedroom Bulb 1 B0CE181403359E4B turning on.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 2 B0CE1814033599A1 updating.
2020-09-14 18:05:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 1 B0CE181403359E4B updating.
2020-09-14 18:05:36 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:36 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: get_response Sengled Request getting response NON-async.
2020-09-14 18:05:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sengledapi doing I/O at custom_components/sengledapi/sengledapi/sengled_request.py, line 39: r = requests.post(self._url, headers=self._header, data=self._payload)
2020-09-14 18:05:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: get_response Sengled Request getting response NON-async.
2020-09-14 18:05:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sengledapi doing I/O at custom_components/sengledapi/sengledapi/sengled_request.py, line 39: r = requests.post(self._url, headers=self._header, data=self._payload)
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 2 B0CE1814033599A1 updating.
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Sengled Bulb Bedroom Bulb 1 B0CE181403359E4B updating.
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-14 18:05:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-14 18:05:41 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceInfos': [{'gatewayUuid': 'B0:CE:18:24:51:71', 'gatewayName': 'Hub', 'routerBssid': '02:00:00:00:00:00', 'activeTime': '2018-12-26 22:21:25', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.1.20', 'isOnline': 1, 'ssid': 'RTK 11n AP', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/Kiev', 'lampInfos': [{'deviceUuid': 'B0CE1814033599A1', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 2', 'colorMode': '3', 'isOnline': '1', 'version': '9', 'onCount': '270', 'typeCode': 'E11-G13', 'onoff': '0'}}, {'deviceUuid': 'B0CE181403359E4B', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 1', 'colorMode': '3', 'isOnline': '1', 'version': '9', 'onCount': '289', 'typeCode': 'E11-G13', 'onoff': '0'}}]}], 'success': True}
2020-09-14 18:05:41 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Light Bedroom Bulb 2 updating.
2020-09-14 18:05:41 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceInfos': [{'gatewayUuid': 'B0:CE:18:24:51:71', 'gatewayName': 'Hub', 'routerBssid': '02:00:00:00:00:00', 'activeTime': '2018-12-26 22:21:25', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.1.20', 'isOnline': 1, 'ssid': 'RTK 11n AP', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/Kiev', 'lampInfos': [{'deviceUuid': 'B0CE1814033599A1', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 2', 'colorMode': '3', 'isOnline': '1', 'version': '9', 'onCount': '270', 'typeCode': 'E11-G13', 'onoff': '0'}}, {'deviceUuid': 'B0CE181403359E4B', 'deviceClass': 1, 'supportAttributes': '0,1,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'E11-G13', 'brightness': '242', 'activeTime': '2018-12-26 22:21:30', 'name': 'Bedroom Bulb 1', 'colorMode': '3', 'isOnline': '1', 'version': '9', 'onCount': '289', 'typeCode': 'E11-G13', 'onoff': '0'}}]}], 'success': True}
2020-09-14 18:05:41 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] Light Bedroom Bulb 1 updating.
```

**Comment by jfarmer08** [comment]
Thank you I will address that.

**Comment by brendan41357** [comment]
I am also experiencing a similar issue. What is strange is despite the error message, the tasks all work. The bulbs still turn on or off, any color settings actually set to the bulb, same with brightness, etc. Though I have noticed if the error occurs in the middle of a script it stops any future actions in that script.

```
2020-09-17 09:11:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1640933048] unsupported operand type(s) for /: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 249, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 233, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 471, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 444, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/config/custom_components/sengledapi/light.py", line 106, in hs_color
    return colorutil.color_RGB_to_hs(self._rgb_color_r,self._rgb_color_g,self._rgb_color_b)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 358, in color_RGB_to_hs
    return color_RGB_to_hsv(iR, iG, iB)[:2]
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 352, in color_RGB_to_hsv
    fHSV = colorsys.rgb_to_hsv(iR / 255.0, iG / 255.0, iB / 255.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2020-09-17 09:12:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1640933048] unsupported operand type(s) for /: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 249, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 233, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 471, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 444, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/config/custom_components/sengledapi/light.py", line 106, in hs_color
    return colorutil.color_RGB_to_hs(self._rgb_color_r,self._rgb_color_g,self._rgb_color_b)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 358, in color_RGB_to_hs
    return color_RGB_to_hsv(iR, iG, iB)[:2]
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 352, in color_RGB_to_hsv
    fHSV = colorsys.rgb_to_hsv(iR / 255.0, iG / 255.0, iB / 255.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2020-09-17 09:12:12 INFO (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_color_bulb] SengledApi: Set Color R 255 G 127 B 255
2020-09-17 09:12:12 INFO (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_color_bulb] SengledApi: Set Color R 255 G 127 B 255
2020-09-17 09:12:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1640933048] unsupported operand type(s) for /: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 249, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 233, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 471, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 444, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/config/custom_components/sengledapi/light.py", line 106, in hs_color
    return colorutil.color_RGB_to_hs(self._rgb_color_r,self._rgb_color_g,self._rgb_color_b)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 358, in color_RGB_to_hs
    return color_RGB_to_hsv(iR, iG, iB)[:2]
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 352, in color_RGB_to_hsv
    fHSV = colorsys.rgb_to_hsv(iR / 255.0, iG / 255.0, iB / 255.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2020-09-17 09:12:22 ERROR (zeroconf-Engine-264) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 444, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/config/custom_components/sengledapi/light.py", line 106, in hs_color
    return colorutil.color_RGB_to_hs(self._rgb_color_r,self._rgb_color_g,self._rgb_color_b)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 358, in color_RGB_to_hs
    return color_RGB_to_hsv(iR, iG, iB)[:2]
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 352, in color_RGB_to_hsv
    fHSV = colorsys.rgb_to_hsv(iR / 255.0, iG / 255.0, iB / 255.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2020-09-17 09:12:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 583, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 307, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 444, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/config/custom_components/sengledapi/light.py", line 106, in hs_color
    return colorutil.color_RGB_to_hs(self._rgb_color_r,self._rgb_color_g,self._rgb_color_b)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 358, in color_RGB_to_hs
    return color_RGB_to_hsv(iR, iG, iB)[:2]
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 352, in color_RGB_to_hsv
    fHSV = colorsys.rgb_to_hsv(iR / 255.0, iG / 255.0, iB / 255.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

```

All these errors came from two service call attempts, one to turn the light on, the next to set the color.

Using the latest version of Sengled API and [https://www.bestbuy.com/site/sengled-smart-led-multicolor-a19-starter-kit-4-pack-multicolor/6373497.p?skuId=6373497](url) for the hub/bulbs.

**Comment by jfarmer08** [comment]
Please update to the lastest release this should help with your issue.
https://github.com/jfarmer08/ha-sengledapi/releases

**Comment by brendan41357** [comment]
Yes that seems to have fixed the issue and there are no more error messages
on the latest release. Thank you so much for your work on this project!

**Comment by jfarmer08** [comment]
@brendan41357 Thank you.
