### ISSUE TITLE
[Bug] Bulb entites not being created

### ISSUE THREAD

**Issue by TheSpad** [jfarmer08/ha-sengledapi#33]
Docker
Home Assistant 0.115.3
Not using HACS
```
2020-09-28 10:29:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-28 10:29:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceList': None, 'sceneList': None, 'customerId': 12345, 'success': True}
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Store the logged in account object for the platforms to use
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Start up lights, switch and binary sensor components
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi.light] Creating new Sengled light component
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List All Bulbs.
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-28 10:29:38 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List Device return {'gatewayUuid': 'B0:CE:18:20:17:A9', 'gatewayName': 'Hubert', 'routerBssid': '92:2A:A8:18:C1:23', 'activeTime': '2019-05-05 15:56:26', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.0.66', 'isOnline': 1, 'ssid': 'Corp', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/London', 'lampInfos': [{'deviceUuid': 'B0CE181403046F83', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 1', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '929', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}, {'deviceUuid': 'B0CE1814030471D0', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 2', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '910', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}]}
```
configuration.yaml
```yaml
sengledapi:
  username: "<username>"
  password: "<password>"
  country: "GB"

logger:
  default: warning
  logs:
    custom_components.sengledapi: debug
```

**Comment by jfarmer08** [comment]
@TheSpad 
If you can use the Master Branch instead of release 1 and test this again. There has been alot of changes and are still testing them.

**Comment by TheSpad** [comment]
Updated to master, still seeing the same thing. Not sure if it should be showing up in the Add Intregrations list, but it's not there either, although it is listed as an integration under Server Info.
```
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceList': None, 'sceneList': None, 'customerId': 12345, 'success': True}
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Store the logged in account object for the platforms to use
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Start up lights, switch and binary sensor components
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.light] Creating new Sengled light component
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List All Bulbs.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List Device return {'gatewayUuid': 'B0:CE:18:20:17:A9', 'gatewayName': 'Hubert', 'routerBssid': '92:2A:A8:18:C1:23', 'activeTime': '2019-05-05 15:56:26', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.0.66', 'isOnline': 1, 'ssid': 'Corp', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/London', 'lampInfos': [{'deviceUuid': 'B0CE181403046F83', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 1', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '929', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}, {'deviceUuid': 'B0CE1814030471D0', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 2', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '910', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}]}
```

**Comment by jfarmer08** [comment]
it currently does not support integrations

You should see more logs. Can you send me those.

**Comment by TheSpad** [comment]
Full output
```
2020-09-28 13:52:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sengledapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb] SengledApi: Initializing Sengled Bulb
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_bulb_flood_motion] SengledApi: Initializing Sengled Flood Motion Bulb
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.bulbs.sengled_color_bulb] SengledApi: Initializing Sengled color Bulb
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_wifi_bulb] SengledApi: Initializing Sengled Wifi Bulb
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_wifi_color_bulb] SengledApi: Initializing Sengled Wifi Color Bulb
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi]
    -------------------------------------------------------------------
    Sengled Bulb Home Assistant Integration Created from Config

    Version: v0.1-beta.18
    This is a custom integration
    If you have any issues with this you need to open an issue here:
    https://github.com/jfarmer08/ha-sengledapi
    -------------------------------------------------------------------
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi] Creating new SengledApi component
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api initializing.
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengled Api initializing async.
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] Sengledapi: async_login
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] async_do_login_request - Sengled Api doing request.
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-28 13:52:35 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_login_response Sengled Request getting response async.
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'ret': 0, 'msg': 'success', 'customerId': <REDCATED>, 'mobileId': <REDCATED>, 'nick_name': '<REDCATED>', 'relative_path': None, 'jsessionId': '0e75b348-1a6d-42aa-b904-f9bf863001dd', 'ucenterAddr': '', 'appServerAddr': '', 'serAddressess': None, 'privacyPolicyStatus': 1}
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi Login {'ret': 0, 'msg': 'success', 'customerId': <REDCATED>, 'mobileId': <REDCATED>, 'nick_name': '<REDCATED>', 'relative_path': None, 'jsessionId': '0e75b348-1a6d-42aa-b904-f9bf863001dd', 'ucenterAddr': '', 'appServerAddr': '', 'serAddressess': None, 'privacyPolicyStatus': 1}
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Connected to Sengled account
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-28 13:52:37 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceInfos': [{'gatewayUuid': 'B0:CE:18:20:17:A9', 'gatewayName': 'Hubert', 'routerBssid': '92:2A:A8:18:C1:23', 'activeTime': '2019-05-05 15:56:26', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.0.66', 'isOnline': 1, 'ssid': 'Corp', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/London', 'lampInfos': [{'deviceUuid': 'B0CE181403046F83', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 1', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '929', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}, {'deviceUuid': 'B0CE1814030471D0', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 2', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '910', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}]}], 'success': True}
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: Sengled Request initializing.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: async_get_response Sengled Request getting response async.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengled_request] SengledApi: data from async_get_response {'messageCode': '200', 'info': 'OK', 'description': '正常', 'deviceList': None, 'sceneList': None, 'customerId': <REDCATED>, 'success': True}
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Store the logged in account object for the platforms to use
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi] SengledApi Start up lights, switch and binary sensor components
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.light] Creating new Sengled light component
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List All Bulbs.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: Get Devices.
2020-09-28 13:52:40 DEBUG (MainThread) [custom_components.sengledapi.sengledapi.sengledapi] SengledApi: List Device return {'gatewayUuid': 'B0:CE:18:20:17:A9', 'gatewayName': 'Hubert', 'routerBssid': '92:2A:A8:18:C1:23', 'activeTime': '2019-05-05 15:56:26', 'gatewayVersion': 'V4.3.9', 'gatewayIp': '192.168.0.66', 'isOnline': 1, 'ssid': 'Corp', 'iterationCode': '2', 'category': 'element', 'gatewayProductCode': None, 'longitude': None, 'latitude': None, 'timeZone': 'Europe/London', 'lampInfos': [{'deviceUuid': 'B0CE181403046F83', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 1', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '929', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}, {'deviceUuid': 'B0CE1814030471D0', 'deviceClass': 1, 'supportAttributes': '0,1,2,3,4', 'attributes': {'deviceRssi': '5', 'productCode': 'Z-DevProductCode-Def', 'brightness': '255', 'activeTime': '2019-05-05 15:56:32', 'name': 'Bulb 2', 'colorMode': '2', 'isOnline': '1', 'version': '23', 'onCount': '910', 'typeCode': 'Z01-A60EAE27', 'onoff': '1', 'colorTemperature': '58'}}]}
```

**Comment by jfarmer08** [comment]
This is very odd. It does not seem to be doing anything after it get the list of Devices. It does return 2 bulbs

**Comment by jfarmer08** [comment]
Do you have any errors in your log/?

**Comment by TheSpad** [comment]
Nothing related, just a couple of warnings for losing connection to Chromecasts going on and off.

**Comment by jfarmer08** [comment]
I it could be an issue with mqtt support. Not sure since I only us hacs, I will look into it.

**Comment by TheSpad** [comment]
OK, installed via HACS and now the entities are showing up, however controls aren't working.

It looks like there's no geo endpoint for GB/UK maybe? Is there like a default/generic endpoint to use instead as it throws an error with no country specified in the config.
```
2020-09-29 19:25:37 INFO (MainThread) [custom_components.sengledapi.sengledapi.devices.bulbs.bulb] Bulb Bulb 1 B0CE181403046F83 setting brightness.
2020-09-29 19:25:37 INFO (MainThread) [custom_components.sengledapi.sengledapi.devices.request] SengledApi: Sengled Request initializing.
2020-09-29 19:25:38 INFO (MainThread) [custom_components.sengledapi.sengledapi.devices.bulbs.bulb] Sengled Bulb Bulb 1 B0CE181403046F83 updating.
2020-09-29 19:25:38 INFO (MainThread) [custom_components.sengledapi.sengledapi.devices.request] SengledApi: Sengled Request initializing.
2020-09-29 19:25:38 INFO (MainThread) [custom_components.sengledapi.sengledapi.devices.request] SengledApi: Sengled Request initializing.
2020-09-29 19:25:38 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 258, in async_do_request
    return await Request(url, payload).async_get_response(jsessionId)
  File "/config/custom_components/sengledapi/sengledapi/devices/request.py", line 53, in async_get_response
    async with session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gb-elements.cloud.sengled.com:443 ssl:<ssl.SSLContext object at 0xffff87dca340> [Name does not resolve]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xffff8d19c0a0>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gb-elements.cloud.sengled.com', port=443): Max retries exceeded with url: /zigbee/device/deviceSetBrightness.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8d19c0a0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 260, in async_do_request
    return Request(url, payload).get_response(jsessionId)
  File "/config/custom_components/sengledapi/sengledapi/devices/request.py", line 39, in get_response
    r = requests.post(self._url, headers=self._header, data=self._payload)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gb-elements.cloud.sengled.com', port=443): Max retries exceeded with url: /zigbee/device/deviceSetBrightness.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8d19c0a0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

**Comment by TheSpad** [comment]
To answer my own question it looks like there's an `eu-elements.cloud.sengled.com` which is valid, so need to specify `EU` as the country code.

**Comment by jfarmer08** [comment]
I dont set a default for the  country code, but it is required. I believe eu would work.

**Comment by jfarmer08** [comment]
If you look at the debug log under Login Response. It might help to the get the country code

**Comment by jfarmer08** [comment]
There is a new release v.1.1. This has a lot of code clean and should address any issues if you can find your country code. I need a better way of find the country code out in feature releases.

**Comment by TheSpad** [comment]
Working well with `EU` country code. Only been able to find `US`, `EU`, `AU`, and `CN` as valid endpoints so far. There is also just `elements.cloud.sengled.com` which may work as a fallback.

**Comment by jfarmer08** [comment]
Great info. I am glad this is working.
