### ISSUE TITLE
[Bug] Install Failure -util/async_.py

### ISSUE THREAD

**Issue by JWhiteUX** [jfarmer08/ha-sengledapi#80]
**Describe the bug**
Similar to Issue #79 — Including more context.

**To Reproduce**
1. Follow README.txt instructions (HACS, Integration, Restart, etc)
2. On Boot… **ERROR** See the following…

**Expected behavior**

**System configuration**
System: HA Proxmox VM
HA Version:  Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221102.1 - latest 
SengledApi Version: 0.2.5

**configuration.yaml**
<img width="430" alt="image" src="https://user-images.githubusercontent.com/12961108/200098503-71d69f3b-f2e6-48e2-a8c1-95137284748e.png">

**home-assistant.log**
```
Logger: homeassistant.setup
Source: util/async_.py:168
First occurred: 7:55:08 PM (1 occurrences)
Last logged: 7:55:08 PM

Error during setup of component sengledapi
Traceback (most recent call last):
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 253, in async_do_request
    return await Request(url, payload).async_get_response(jsessionId)
  File "/config/custom_components/sengledapi/sengledapi/devices/request.py", line 57, in async_get_response
    data = await resp.json()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://element.cloud.sengled.com/zigbee/device/getDeviceDetails.json')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/sengledapi/__init__.py", line 64, in async_setup
    sengledapi_devices = await sengledapi_account.async_get_devices()
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 182, in async_get_devices
    data = await self.async_do_request(url, payload, SESSION.jsession_id)
  File "/config/custom_components/sengledapi/sengledapi/sengledapi.py", line 255, in async_do_request
    return Request(url, payload).get_response(jsessionId)
  File "/config/custom_components/sengledapi/sengledapi/devices/request.py", line 40, in get_response
    r = requests.post(self._url, headers=self._header, data=self._payload)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 180, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/sengledapi/sengledapi/devices/request.py, line 40: r = requests.post(self._url, headers=self._header, data=self._payload)

====================

Logger: homeassistant.util.async_
Source: util/async_.py:180
First occurred: 7:55:08 PM (1 occurrences)
Last logged: 7:55:08 PM

Detected blocking call to putrequest inside the event loop. This is causing stability issues. Please report issue to the custom integration author for sengledapi doing blocking calls at custom_components/sengledapi/sengledapi/devices/request.py, line 40: r = requests.post(self._url, headers=self._header, data=self._payload)
```

**Comment by jfarmer08** [comment]
Check your username or password

**Comment by MWeberSSI** [comment]
The issue was an "old" password that did not meet the new complexity requirements. I changed the PW via the Android app/email/web and now the entities show up. Thanks for the hint.
